name: Fetch URLs from Webpage

on:
  push:
    branches:
      - main  # Adjust this to match your default branch

jobs:
  fetch_urls:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch webpage content
      run: |
        content=$(curl -s http://206.12.88.113/articles-list/)
        echo "$content" > webpage_content.txt

    - name: Parse URLs from content
      run: |
        cat webpage_content.txt | grep -Eo 'href="[^"]+"' | awk -F '"' '{print $2}' > urls.txt
        cat urls.txt
