name: Test Cron Jobs
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build_and_check:
    runs-on: ubuntu-latest
    timeout-minutes: 3 # Set the overall job timeout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Broken Link Checker
        run: npm install -g broken-link-checker

      - name: Run Cron Job
        run: blc http://206.12.88.113/ -fo

#       - name: Handle Timeout
#         if: ${{ job.completed == false }} # Check if the job has not completed
#         run: echo "Job timed out" # Add any actions or commands to handle the timeout
